### ISSUE TITLE
Hi how to add Modules to cmangos?

### ISSUE THREAD

**Issue by william19831103** [talamortis/mangos-tbc#11]
Hi how to add Modules to cmangos?

**Comment by talamortis** [comment]
place the modules in the folder located in src/game/modules

**Comment by yuyu-lovegelin111333** [comment]
@talamortis  , Sir , may you help to released a new version or long time version of Modules . patch ?  which can be suit for their cmangos-tbc latest updating code ?  just a required.,.,
